- menu_name: "Community"

- name: "Subscribe"
  url: "https://forms.academicsinthewild.com/subscribe"
  title: "Subscribe"

- name: "Become a member"
  url: "https://forms.academicsinthewild.com/join-aitw-community"
  title: "Become a member"

- name: "Discord"
  url: "https://discord.gg/hWcA47TNhF"
  title: "Discord"

- name: "Code of conduct"
  url: "/code-of-conduct/"
  title: "Code of conduct"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
